### ISSUE TITLE
Dependencies of dependencies are being installed

### ISSUE THREAD

**Issue by insin** [renke/auto-install-webpack-plugin#2]
I'm seeing dependencies of dependencies being installed in my own app when using this plugin.

e.g., with auto-install-webpack-plugin@1.2.3 if I `require('react-fa')` (which has a dependency on font-awesome), the following happens:

```
webpack building...
npm install --save react-fa
react-fa@4.0.0 node_modules\react-fa
└── font-awesome@4.5.0
npm install --save font-awesome
font-awesome@4.5.0 node_modules\font-awesome
```

If I already have react-fa installed locally when I start my webpack server, then font-awesome will be installed when I start it up.

**Comment by renke** [comment]
Hi @insin,

I just tried to look at the problem and actually failed to run my own (manual) tests so it might take a while for me to fix this problem. I am currently not sure what the future holds for this plugin but a lot of discussion takes place [here](https://github.com/ericclemmons/npm-install-loader/issues/5) which might eventually result in a completely new plugin (or whatever).
